services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: nexusai-postgres
    environment:
      POSTGRES_USER: nexusai
      POSTGRES_PASSWORD: varshith2004
      POSTGRES_DB: nexusai_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nexusai -d nexusai_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nexusai-network

  backend:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile.backend
    container_name: nexusai-backend
    environment:
      DATABASE_URL: postgresql://nexusai:varshith2004@postgres:5432/nexusai_db
      OLLAMA_BASE_URL: http://host.docker.internal:11434
      MLFLOW_TRACKING_URI: http://mlflow:5000
      USE_CLOUD_LLM: ${USE_CLOUD_LLM:-False}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./data:/app/data
    depends_on:
      postgres:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - nexusai-network
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload

  mlflow:
    image: python:3.11-slim
    container_name: nexusai-mlflow
    command: >
      bash -c "pip install mlflow==2.9.2 &&
               mlflow server
               --host 0.0.0.0
               --port 5000
               --backend-store-uri sqlite:///mlflow/mlflow.db
               --default-artifact-root /mlflow/artifacts"
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow:/mlflow
    networks:
      - nexusai-network

  frontend:
    build:
      context: ./frontend
      dockerfile: ../infra/docker/Dockerfile.frontend
    container_name: nexusai-frontend
    ports:
      - "3000:3000"
   
    environment:
      - VITE_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - nexusai-network
    

  ollama:
    image: ollama/ollama:latest
    container_name: nexusai-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    networks:
      - nexusai-network
    profiles:
      - gpu

volumes:
  postgres_data:
  ollama_data:

networks:
  nexusai-network:
    driver: bridge